name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-maybe-push:
    name: build and maybe push images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "torchserve"
            file: "load-tests/docker/torchserve.dockerfile"
            build_contexts: ""
          - name: "nx_net"
            file: "load-tests/docker/nx_net/Dockerfile"
            build_contexts: ""
          - name: "lanx_net"
            file: "load-tests/docker/lanx_net/Dockerfile"
            build_contexts: |
              lanx=./

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/Benjamin-Philip/lanx/load-test-${{ matrix.name }}

      - name: Build and maybe push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: ${{ matrix.file }}
          build-contexts: ${{ matrix.build_contexts }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.output.tags }}
          cache-from: type=gha
          cache-to: typegha,mode=max
