name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-maybe-push:
    name: build and maybe push images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "torchserve"
            context: load-tests/docker
            file: torchserve.dockerfile
            build_contexts: ""
          - name: "nx_net"
            context: load-tests/docker/nx_net
            file: Dockerfile
            build_contexts: ""
          - name: "lanx_net"
            context: load-tests/docker/lanx_net
            file: Dockerfile
            build_contexts: |
              lanx=.

    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/Benjamin-Philip/load-test-${{ matrix.name }}

      - name: Build and maybe push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.file }}
          build-contexts: ${{ matrix.build_contexts }}
          platforms: linux/amd64
          tags: ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
