name: Publish Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  otp: 26.2
  elixir: 1.16.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ env.elixir }}
        otp-version: ${{ env.otp }}

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-elixir-${{ env.elixir }}-otp-${{ env.otp }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix do deps.get, deps.compile

    - name: Generate docs
      run: mix docs

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'doc'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Allow only one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true

    steps:
    - name: Show Context
      run: echo "$GITHUB_CONTEXT"

    - name: Deploy to GitHub Pages
      id: deployment
      preview: ${{ if github.ref != 'refs/heads/main' }}
      uses: actions/deploy-pages@v4.0.5
