name: Benchmark PR
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  otp: 26.2
  elixir: 1.16.2

jobs:
  benchmark:
    name: Benchmark and Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.elixir }}
          otp-version: ${{ env.otp }}

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: bench-${{ runner.os }}-elixir-${{ env.elixir }}-otp-${{ env.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: MIX_ENV=bench mix do deps.get, deps.compile

      - name: Build
        run: MIX_ENV=bench mix compile

      - name: Download previous run
        id: download
        uses: actions/download-artifact@v4
        with:
          name: pr-${{ github.event.number }}
          path: 'benchmarks/profile/saves'
        continue-on-error: true

      - name: Benchmark base
        if: ${{ steps.download.conclusion == 'failure' }}
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}
          mix bench.profile.run --tag base
          git checkout ${{ github.event.pull_request.head.sha }}

      - name: Benchmark head
        run: mix bench.profile.run --tag ${{ github.event.pull_request.head.sha }} --profile

      - name: Upload run
        uses: actions/upload-artifact@v4
        with:
          name: pr-${{ github.event.number }}
          path: 'benchmarks/profile/saves'
          overwrite: true

      - name: Generate Report
        run: |
          mix bench.profile.report
          cat benchmarks/profile/saves/report.md > ${{ env.PR_COMMENT }}

      - name: Comment
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: require('fs').readFileSync('${{ env.PR_COMMENT }}').toString()
            });
